version: "3.8"

services:
  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-baseline
    container_name: fastapi-baseline
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
      - SBER_AUTH=${SBER_AUTH}
    volumes:
      - ./logs:/app/logs
    # Если нужно GPU
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
